"""Cambiar columna body y description a Text

Revision ID: 67ba5f69c5ae
Revises: 7585f9981df4
Create Date: 2024-10-06 21:23:09.770524+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ba5f69c5ae'
down_revision = '7585f9981df4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body',
                    existing_type=sa.VARCHAR(length=123),
                    type_=sa.Text(),
                    nullable=False)
    
    # Cambiar el tipo de columna 'description' en 'topics' a Text
    op.alter_column('topics', 'description',
                    existing_type=sa.VARCHAR(length=123),
                    type_=sa.Text(),
                    nullable=False)
     
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('posts', 'body',
                    existing_type=sa.Text(),
                    type_=sa.VARCHAR(length=123),
                    nullable=False)
    
    op.alter_column('topics', 'description',
                    existing_type=sa.Text(),
                    type_=sa.VARCHAR(length=123),
                    nullable=False)
    # ### end Alembic commands ###
