"""Rename pending columns to pending_for_teacher

Revision ID: 3762f490e040
Revises: f5f5481f41c4
Create Date: 2024-10-06 08:39:41.687652+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3762f490e040'
down_revision = 'f5f5481f41c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
