"""Actualizar author_id con ON DELETE SET NULL

Revision ID: 49f0cfcc1c6a
Revises: 0841ca232d26
Create Date: 2024-09-21 21:18:04.898337+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f0cfcc1c6a'
down_revision = '0841ca232d26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('posts_author_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('topics', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('topics_author_id_fkey', 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key('topics_author_id_fkey', 'topics', 'users', ['author_id'], ['id'])
    op.alter_column('topics', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'])
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
