"""Unificar columna pending_for_teacher

Revision ID: 7585f9981df4
Revises: 3762f490e040
Create Date: 2024-10-06 08:49:57.354537+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7585f9981df4'
down_revision = '3762f490e040'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('pending_for_teacher', sa.Boolean(), nullable=True))
    op.drop_column('topics', 'pending_for_professor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('pending_for_professor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('topics', 'pending_for_teacher')
    # ### end Alembic commands ###
