"""añadir columna rol a posts y a topics bd

Revision ID: 0841ca232d26
Revises: 64034456b8d7
Create Date: 2024-09-21 09:32:09.596008+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0841ca232d26'
down_revision = '64034456b8d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('topics', sa.Column('role', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'role')
    op.drop_column('posts', 'role')
    # ### end Alembic commands ###
