"""añadir columna boolean con pendings

Revision ID: f5f5481f41c4
Revises: 49f0cfcc1c6a
Create Date: 2024-10-04 08:44:09.256680+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f5481f41c4'
down_revision = '49f0cfcc1c6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('pending_for_teacher', sa.Boolean(), nullable=True))
    op.add_column('topics', sa.Column('pending_for_teacher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'pending_for_teacher')
    op.drop_column('posts', 'pending_for_teacher')
    # ### end Alembic commands ###
